apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: nats-line-notify-subscriber

resources:
  - deployment.yaml

configMapGenerator:
  - name: nats-line-notify-subscriber-configmap
    envs:
      - config/config.env

secretGenerator:
  - name: nats-line-notify-subscriber-secret
    envs:
      - secret/secret.env
    type: Opaque
