name: Publish Docker image by tag
on:
  push:
    tags:
      - v*
jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set image tag
        run: |
          # use tag for image_tag, 'v1.2.3' -> '1.2.3'
          IMAGE_TAG=${GITHUB_REF##*/v}
          echo ::set-env name=IMAGE_TAG::${IMAGE_TAG}

      - name: Build and Publish
        run: |
          docker buildx build \
            --push \
            --platform linux/arm/v7,linux/amd64 \
            -t ${{ github.repository }}:latest \
            -t ${{ github.repository }}:${IMAGE_TAG} .
